# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'quizzApp' do
  pod 'ProgressHUD'
  pod 'SnapKit', '~> 4.0'
  
end
